[tool.poetry]
name = "map-of-physics"
version = "0.1.0"
description = ""
authors = ["Jasper Seehofer <jasper@gulp-wagner.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
